name: "Build images"
on:
  push:
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
   
      - name: "Run nix flake check"
        run: nix flake check
      - name: "Check nix formatting"
        run: find . -iname '*.nix' | xargs nix run nixpkgs/nixos-unstable#nixfmt -- --check
      
      - name: "Build virtualbox"
        run: |
          nix build .#virtualbox
          cp -Lr ./result virtualbox

      - name: "Build install iso"
        run: |
          nix build .#install-iso
          cp -Lr ./result/iso install-iso

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Upload virtualbox image to minio
        uses: 49nord/action-minio-mirror@v1
        with:
          host: ${{ secrets.ARTIFACT_UPLOAD_HOST }}
          bucket: ${{ secrets.ARTIFACT_UPLOAD_BUCKET }}
          src: ./virtualbox/
          dst: virtualbox-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}

      - name: Upload install iso to minio
        uses: 49nord/action-minio-mirror@v1
        with:
          host: ${{ secrets.ARTIFACT_UPLOAD_HOST }}
          bucket: ${{ secrets.ARTIFACT_UPLOAD_BUCKET }}
          src: ./install-iso/
          dst: install-iso-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
